project:
  type: website

website:
  title: "SLR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About this book
      - href: toc.qmd
        text: Table of Contents
  sidebar:
    contents:
      - text: Introduction
        href: intro.qmd
      - text: Steps of SLR
        href: steps.qmd
      - text: Topics of SLR
        href: topics.qmd
      - text: Databases
        href: database.qmd
      - text: Keywords and search
        href: search.qmd
      - text: Abstract screening
        href: abstract-screening.qmd
      - text: Full text retrieval
        href: retrieval.qmd
      - text: Full text screening
        href: pdf-screening.qmd
      - text: Introduction to coding qualitative data
        href: intro_coding.qmd
      - text: Developing codebooks
        href: develop_codebook.qmd
      - text: Coding practice
        href: coding_practice.qmd
      - text: Inter-coder reliability
        href: icr.qmd
      - text: Roles or members
        href: roles.qmd
  page-footer:
    left: "Copyright 2026, Faisal Mustafa"
    center: Mustafa, F. (2025). <em> A practical guide to conducting a robust systematic literature review research </em>. Github. https://faisalmustafa.github.io/SLR-Book/
    right:
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
    background: "#4097C2"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

citeproc: true
bibliography: references.bib
csl: apa.csl
