---
title: "About this book"
format: html
---

Learning this type of research was quite a journey for myself, and thus I do not intend to let this process goes to waste because not all academicians have a learning chance as I did. Therefore, the purpose of this book is to describe the process of Systematic Literature Review research as I learned it through reading and collaborations. Allow me to share how I learned this type of research before I describe how this book is presented.

The process goes back to late 2022 when I started by PhD at the UNSW Sydney in Summer Semester 2023. I only have a chance to meet my supervisors briefly once before they both went on their summer holiday. I was advice to review the literature using NVIVO to decide whether I needed to change the focus of my research. I started by learning NVIVO by watching a 12 hour NVIVO tutorial, which in my case was adequate to start my literature review. I send a report to my supervisors after one month. I received comments from my supervisors and one of them indicated that my work could be published. I started reading more and watching more vidoes on conducting systematic literature review research. I finally published the result of this systematic literature review research in a reputable journal as my first systematic literature review paper.

In 2024 I was involved in a UNESCO project related to digital transformation in higher education led by my supervisor, who put much focus on reliability and accuracy. I was offered to work in the project as a research assistant after the project started, so I was not involved from the beginning. I learned more about coding process involving multiple cycle inter-coder reliability attempts to ensure that all coders had adequate levels of agreement in coding the literature. 

Finally, I was involved to work in a big systematic literature review project related to culturally responsive pedagogy, also led by my supervisor. This project run the entire 2025 with weekly meeting. There were two publication intended from the project, one was to conceptualize the culturally responsive pedagogy, and another was to determine how pre-service teachers were prepared to teach diverse students. I learned a lot from this process, especially on making the systematic literature review research accurate, reliable, and reproducable. After completing this project, I was confident that I can start mentoring novice systematic literature review researchers.

This online version book reflects my own understanding of what systematic literature review research is and how to make it entirely systematic, reliable, accurate, and reproducable. Therefore, there is no citation used in this book because I did not refer to any sources when writing it, unless it is very necessary or when readers need to read some texts to understand the point that I was making. Since the book emphasizes on practicality, the language used was not always academic; thus, you can find casual expressions used very often in this book. I hope you don't mind.