---
title: "Step 2 in Coding: Coding practice"
format: html
title-block-banner: "#4097C2"
title-block-banner-color: white
bibliography: references.bib
csl: apa.csl
---

After the codebook is developed, probably by researcher leading team members, all members who are responsible to code the data should have one or two cycles of coding practice. This process is necessary to ensure each team member has the same understanding of the research questions, coding framework, and coding protocol. Therefore, before the coding practice, the coder team leader needs to dicuss the framework comprehensively. The coding practice should be conducted together, so the discussion can done immediately when necessary, which leaves little room for missunderstanding. 

The number of articles or interviews required for coding practice depends on several factors. First, the framework used might be familiar for the reseachers. Familiar framework is easier to understand, and thus it will not need to much coding practice to be able to code the data accurately. Second, the coding practice depends on the complexity of the project. The projects which uses simpler framework such as @bronfenbrenner2001 framework will need less practice than projects with CHAT framework. Thirds, coding practice should consider researchers' expertise with the research topics. Researchers who have previously worked with the same topic will be able to code accurately with less practice then researchers who have just been involved in the project. Finally, researchers who have worked in other projects involving qualitative data coding can learn to code in another project easier than researchers who just learn this process for the first time.