---
title: "Selecting databases for systematic literature review"
format: html
title-block-banner: "#4097C2"
title-block-banner-color: white
---

## Database criteria

The rule of thumb is that the database used needs to be indexing databases which include journals or book chapters after assessment involving management and content quality. Google Scholar includes any academic publication without any assessment, and thus they are not elligible to be selected for systematic literature review research. Another indexing platform is DOAJ, which indexes journals after an assessment; however, the assessment tend to focus only on journal management, not the quali-ty of research and reporting. Thus, DOAJ is also not elligible for systematic literature review paper. One of a good example is Scopus, because it includes journals and book chapters after a series of assessment by expert team with well-established selection criteria targetting management and content quality, even extended to journal standing (i.e., citedness of journal articles in Scopus  and its editor reputation).

## Discipline-specific and general databases

In addition, database selection needs to consider the topic of systematic literature review research. I believe that you are well aware of the discipline-speficif databases in your research area. For example, PubMed is a discipline-specific database in medical and health research, and IEEE is a popular database for computer sciences. In my case, my research is around education, and thus I often use ProQuest Education as the discipline-specific database for systematic literature review research.

In addition to these discipline-specific databases, Scopus and Web of Science are two general databases which include publications in various topics. Therefore, these two databases should always be considered when conducting systematic literature review research. 

## Access to databases

I understand that not all researchers have access to those databases. Higher institutions in many countries could not afford subscription fee to provide access of these databases to their faculties. However, this problem can be navigated through research collaboration.

Students in the top 100 university most likely have access to these databases. The list of these universities can be accessed here <a href = "https://www.topuniversities.com/world-university-rankings" target = '_blank'> https://www.topuniversities.com/world-university-rankings</a>. First, list potential collaborators, the persons you or other team members know, and check their university library website to determine whether they have access to the databases that you have selected. Afterward, send them an email (one person at a time because you do not want to end up having a large team) inviting them to collaborate in a research project and explaining what their role is. Since systematic literature review research might not be their priority, try not to give them any homework, as in the following email example:

<div style="font-size: 12px; padding-left: 36px; padding-right: 36px" > 
Dear ...,

I hope you are doing well with your study at ....

We are working on systematic literature review research on ....., which we believe is in line with your research interest. Unfortulately, we do not have access to Scopus, Web of Science, and ProQuest databases. Therefore, we would like to invite you to the team and your responsibility in the team is to run the search in these databases since you have access to them through your university library. We understand that you might be busy, so we will also provide keywords for the search.

After we screen abstract of the papers you provide, we need your help to download the paper. We will list the DOI of the papers to help you perform this task easily.

In addition, our research is financially supported by my institution, and I will be able to claim 20 hours for you with 20 USD an hour. If you agree to be part of our team, the work will start on ..... You will be listed as the third co-author in the paper which we will submit for publication in a Scopus-indexed journal.

I'm looking forward to hearing from you soon.

Regards,

</div>

After sending the email, give your potential collaborator several days to respond before sending the email to another potential collaborator. You can also indicate how many days you give them to respond in your email.
