---
title: "Full text screening"
format: html
title-block-banner: "#4097C2"
title-block-banner-color: white
bibliography: references.bib
csl: apa.csl
---

This second screening phase is the most important phase to eliminate articles which fall outside the focus of the study. The objective of full text screening is to determine if the articles meet the inclusion and exclusion criteria by scanning the full text. Therefore, I propose that the screening process is combined with quality appraisal.

Quality appraisal is the process of assessing the quality of a publication. Some rubrics for quality appraisal have been developed in previous studies. Some rubrics target the quality of research reported in the publication, and the others focus on the quality of reporting. In our recent research, we attempted to combine these two spectrum to create our own quality appraisal rubric [see @nguyen2026]. The rubric is provided in the following.

<table style="width:100%">
  <tr>
    <th>No</th>
    <th>Items</th>
    <th>Target</th>
    <th> Yes (1), No (0) </th>
  </tr>
  <tr>
    <td>1</td>
    <td>Are the research questions/objectives clearly and appropriately defined?</td>
    <td>The quality of reporting</td>
    <td> </td>
  </tr>
  <tr>
    <td>2</td>
    <td>Is the research design clearly presented in the article?</td>
    <td>The quality of reporting</td>
    <td> </td>
  </tr>
  <tr>
    <td>3</td>
    <td>Is the research design strong enough for the research questions/objectives?</td>
    <td>The quality of research</td>
    <td> </td>
  </tr>
  <tr>
    <td>4</td>
    <td> Is the sampling strategy appropriately justified?</td>
    <td>The quality of reporting</td>
    <td> </td>
  </tr>
  <tr>
    <td>5</td>
    <td> Is the number of cases/sample size adequate?</td>
    <td>The quality of reseach</td>
    <td> </td>
  </tr>
  <tr>
    <td>6</td>
    <td>Does the article clearly describe the setting of data collection?</td>
    <td>The quality of reporting</td>
    <td> </td>
  </tr>
  <tr>
    <td>7</td>
    <td>Is/Are the method(s) of data collection clearly presented in the article?</td>
    <td>The quality of reporting</td>
    <td> </td>
  </tr>
  <tr>
    <td>8</td>
    <td> Is the theoretical framework clearly defined in the article?</td>
    <td>The quality of reporting</td>
    <td> </td>
  </tr>
  <tr>
    <td>9</td>
    <td> Is the theoretical framework appropriate for the research questions/objectives?</td>
    <td>The quality of research</td>
    <td> </td>
  </tr>
  <tr>
    <td>10</td>
    <td>Is/Are the method(s) of data analysis appropriate for addressing the research questions/objectives?</td>
    <td>The quality of research</td>
    <td> </td>
  </tr>
  <tr>
    <td>11</td>
    <td> Is/Are the method(s) of data analysis clearly presented?</td>
    <td>The quality of reporting</td>
    <td> </td>
  </tr>
  <tr>
    <td>12</td>
    <td>Is/Are the research question(s) or objective(s) answered?</td>
    <td>The quality of reporting</td>
    <td> </td>
  </tr>
  <tr>
    <td>13</td>
    <td> Are the discussion/conclusion(s)/ implication(s) data appropriate?</td>
    <td>The quality of reporting</td>
    <td> </td>
  </tr>
  <tr>
    <td>14</td>
    <td> Is there evidence of attention to ethical issues?</td>
    <td>The quality of research</td>
    <td> </td>
  </tr>
</table>

The advantage of doing quality appraisal in the full-text screening is that like *killing two birds with one stone*. Completing the rubric requires scanning many parts of the articles, so any articles which do not fall into the criteria will be spotted. Therefore, no additional effort is necessary to exclude the articles after completing the quality appraisal rubric. 

## Reliability of full text screening and quality appraisal

When the full text screening is conducted by more than one team members, which is recommended, the team members should practice screening one or two papers together then complete at least 10 papers individually. To ensure all team members understand the inclusion/exclusion criteria and rubric, an inter-rater reliability needs to be calculated from these 10 articles. For this purpose, the excluded article can be scored 0.

