---
title: "Full text retrieval"
format: html
title-block-banner: "#4097C2"
title-block-banner-color: white
---

Full text retrieval process should be straightforward if your institution have adequate subscription. As previously mentioned, the researcher team or at least one of the team members needs to have access to non-open access publishers so they can retrieved all articles selected after the abstract screening. In this section, I want to provide some advice to make this process more efficient and helpful for further process.

## Dividing articles by access
If the project involve one team member who have access to non-open access full texts and is responsible only for database search and full text retrieval, the articles need to divided into two groups. The first group consists of open access articles, which will be donwloaded by other team members and the other group consists of articles which cannot be accessed by these members. This will make the process faster. 

## Naming the files
To easily find and refer to the articles, make sure to include Article ID in the full text file name, for example "Article001 Mustafa 2024 The use of..." or "ART001 Mustafa 2024 The use of..." Therefore, when we need to discuss an article in team meeting, we can refer to the Article ID, such as 'Please look at article 5 (Article005 or ART005)'. In addition, the Article ID can be added to the label in the reference manager that we use (e.g., EndNote, Mendeley, Zotero, etc.), which will make it easier to refer to the coded article during the writing up process.

## No access articles 
There will be some articles which cannot be accessed regardless of the level of access given by a reputable institution. In my experience, such articles are never high quality articles. However, if the article is required, there are some steps which can be taken to have access to the article. First, a library usually have inter-library loan