---
title: "Determining Topics for Systematic Literature Review"
format: html
title-block-banner: "#4097C2"
title-block-banner-color: white
---

The first step of conducting systematic literature review research is determining the topic for the research. This topic can come from one of the following activities or efforts. 

First, when you notice that there is an inconsistency in the literature about how a concept is defined, there is a potential to establish a standard conceptualization through systematic literature review research. In my case, when I was doing a UNESCO project on digital transformation in higher education, my team and I found that many reseachers used the word "innovation" to refer to technology-integrated teaching approaches. According to our team, some teaching methods were not new enough to be considered innovative. The inconsistent use of "innovation" in this context was expected because innovation in digital transformation has not been adequately conceptualised. Therefore, systematic literature review research can be used to conceptualize innovation in digital transformation.

Second, many newly emerging topics in the literature have not been reviewed systematically. Although systematic literature review papers have been published in these topics, most of them review studies in general. Reviews in specific context are usually available much later. Therefore, there are many potentials for systematic literature review research for such topics as AI in specific context. For example, the use of AI in lesson planning, writing feedback, or speaking assessment might still be open for systematic literature review research.

Another source of idea for systematic literature review research might come from a curiosity or the need for information which is not straightforwardly available in the literature. For example, I was trying to translate a scale from English into Bahasa Indonesia. I searched the literature to find the translation procedure or process for this purpose, but I did not find any. At that moment, I knew that I could conduct a systematic literature review research to determine how educational researchers translated their scales for research purpose from one language to another.

Finally, topics for the systematic literature review can also be explored from other previous systematic literature review. All research has shortcomings, which can provide a gap for further systematic literature review. Authors usually reveal this aspect in the discussion or conclusion section of the systematic literature review papers.